site_name: IAM Docs
# site_url: https://iam-docs.pro
theme: material

#   features: 
#     - navigation.tabs
#     - navigation.sections
#     - toc.integrate
#     - navigation.top
#     - search.suggest
#     - search.highlight
#     - content.tabs.link
#     - content.code.annotation
#     - content.code.
#   language: en
#   palette:
#     - scheme: default
#       toggle: 
#       icon: material/toggle-switch-off-outline
#       name: Switch to dark mode
#       primary: teal
#       accent: purple 
#     - scheme: slate
#       toggle: 
#       icon: material/toggle-switch
#       name: Switch to light mode
#       primary: teal
#       accent: lime 

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social: 
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/vassily-lapitsky-b4236a16/

copyright: |
  &copy; 2023